services:
  - type: web
    name: jbmotos-api
    env: docker
    plan: free
    dockerfile: Dockerfile
    port: 8080
    buildCommand: "mvn clean install"
    startCommand: "java -jar target/jbmotos-0.0.1-SNAPSHOT.jar"